# Jekyll Settings
excerpt_separator: <!--more-->

name: Brokenhaze
url: http://brokenhaze.com
description: Systems Engineering

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']